# Generated by Django 4.1.1 on 2022-09-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Password",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=200)),
                ("email", models.CharField(blank=True, max_length=100)),
                ("image_url", models.URLField(blank=True, max_length=400)),
            ],
        ),
    ]
